sm8250-common: Add com.android.hotwordenrollment.common.util library
Fixes:
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.android.hotwordenrollment.xgoogle, PID: 4331
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/hotwordenrollment/common/EnrollmentUtil;
E AndroidRuntime: 	at com.android.hotwordenrollment.common.EnrollmentService.onCreate(EnrollmentService.java:59)
E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.android.hotwordenrollment.common.EnrollmentUtil
E AndroidRuntime: 	... 10 more

Change-Id: I5e9605a3ecb9ec080aed554c1541ded9f25c188b